branch-defaults:
  master:
    environment: tweetmap
global:
  application_name: TwitterMap
  branch: null
  default_ec2_keyname: TejasCloud
  default_platform: Python 2.7
  default_region: us-west-2
  profile: null
  repository: null
  sc: git
